### ISSUE TITLE
Client side only execution

### ISSUE THREAD

**Issue by artlovecode** [Unleash/unleash-client-node#105]
Are there any plans to support purely client side execution? I'm running into issues using this library clientside due to calls to `fs`

**Comment by ivarconr** [comment]
Not short term, but it's on the road-map. 

The recommended setup today is to have a small proxy between clients (web, apps) and the unleash-server. Clients should request toggles for a given unleash-context to avoid exposure of all toggles with their internal configurations to all users.

**Comment by artlovecode** [comment]
Fair enough, thanks for the quick response
