### ISSUE TITLE
Events modules are missing from package.json

### ISSUE THREAD

**Issue by zivyatziv** [Unleash/unleash-client-node#109]
I just checked out the client and tried to run it.
![image](https://user-images.githubusercontent.com/39673349/56490981-b51c4180-64ef-11e9-9b62-81cb9eb3022e.png)

I've noticed that the [package.json](https://github.com/Unleash/unleash-client-node/blob/master/package.json) does not contain any reference for it.

Have a good day,
ZY

**Comment by SimenB** [comment]
`events` is a node core module: https://nodejs.org/api/events.html

This module is a library written in TypeScript, so you don't run it. You can run the examples if you want: https://github.com/Unleash/unleash-client-node/tree/master/examples. Make sure to build first though, so you have js and not ts :)
