### ISSUE TITLE
Supporting feature toggle strategies that explicitly 'deny' access

### ISSUE THREAD

**Issue by TimNZ** [Unleash/unleash-client-node#144]
Use case is pretty straight forward.
I want to have a default strategy which enables for all, and a 'deny' strategy i.e. userWithId, to deny the feature to those specific users.

This could be very simple improvement - support a 'mode' on the feature toggle strategy definition, defaults to 'allow', and can change to 'deny'.

What do you think?

Happy to do a PR on server and node client.

'deny' strategies would be evaluated first as they would take precedence over 'allow' strategies.

**Comment by ivarconr** [comment]
We are currently testing strategy constraints with selected clients. This will solve this exact use case and scheduled to be part of v4. https://github.com/Unleash/unleash/issues/442

**Comment by TimNZ** [comment]
Cool, thanks.
