### ISSUE TITLE
Support for setting headers dynamically

### ISSUE THREAD

**Issue by SecretBase** [Unleash/unleash-client-node#151]
## Background
I have a oauth2 authorization server to let registered oauth2 clients performing client credential grant. 
https://tools.ietf.org/html/rfc6749#section-4.4

I want to securing unleash client endpoint by verifying a `jwt` from the Authorization header.

## Problems
Since the unleash client only initialize once. The `customHeaders` still remain static the rest of the up coming request.

## Proposed Solution
I was wondering adding a feature to setting headers dynamically upon request. Like accepting a callback that return a Promise resolve as a header object. By doing that I can get a new access token when there are requests to the unleash server's client endpoint.

example
```js
const { Unleash } = require('unleash-client');

const instance = new Unleash({
    appName: 'my-app-name',
    url: 'http://unleash.herokuapp.com',
    headers: async () => {
        const { access_token, token_type } = await oauthToken(); // Request to an oauth2 authorization server
        return {
            Authorization: `${token_type} ${access_token}`,
        };
    },
});
```

I will be so grateful anyone can give me some guidance/advice ? So I can make a PR for that.

**Comment by ivarconr** [comment]
Hi, thanks this is aligned with a similar problem I want to solve soon. 

I would hovever like the headers to be a function (or a static object as today), and not require it to be a promise. You are free to use async functions inside that function of course.

**Comment by ivarconr** [comment]
I thought a bit more on this, and you are right. It should be an `async` function and I think it should be a separate configuration options (and not try to retro-fit it in to existing `customHeaders` option). 

Would a good name for this option be `customHeadersFunction`? 

If this option is defined it should take precedence over the `customHeaders` option.

**Comment by SecretBase** [comment]
sound good to me.

Will create a Pull Request within couple days.
