### ISSUE TITLE
Create a parameter on initialize function to indicate what features must be loaded

### ISSUE THREAD

**Issue by fredpolicarpo** [Unleash/unleash-client-node#154]
I'm using this API on AWS Lambda context, and there are some cases where I need to look at only some features, but the initialize function always loads all of them. 

So, it will be more performatic if I can pass a list of needed features as a parameter for the `initialize` function, so that it loads just theses functions instead of all of them.

**Comment by ivarconr** [comment]
I'm not sure if this will help much as loading the `feature toggles` still require a fetch to Unleash. The only way I can see loading just a defined set of `feature toggles` could to be more efficient if you have a lot of toggles (> 500) defined. 

You can implement your own [custom repository](https://github.com/Unleash/unleash-client-node#custom-repository) which uses the [namePrefix parameter](https://unleash.github.io/docs/api/client/features) to limit the toggles returned. 

Example:
http://unleash.herokuapp.com/api/client/features?namePrefix=Demo

I have some ideas on how one could Unleash together with AWS lambda more efficiently, will write an article about this soon.

**Comment by ivarconr** [comment]
Will be tracked in #148. 

We plan to add more custom query params (also support for tags) in a later version of the SDK
