### ISSUE TITLE
Request.js has been deprecated

### ISSUE THREAD

**Issue by zivyatziv** [Unleash/unleash-client-node#169]
https://github.com/request/request#deprecated

Also, the official request.js has published a list of alternatives:
https://github.com/request/request/issues/3143

I've found in one of the comments someone who created a list of comparison by features, it could be useful:
https://github.com/sindresorhus/got#comparison.

On a personal note, I've always used `axios`, it has always been my go-to.

**Comment by ivarconr** [comment]
Thanks for informing about this.

**Comment by andreas1327250** [comment]
Maybe use axios as already implemented in this PR for the frontend-version?
https://github.com/Unleash/unleash-client-node/pull/108

**Comment by ivarconr** [comment]
`axios` is nice, but it is rather large. I want to see if we can get away with some isomorphic fetch approaches.

**Comment by zivyatziv** [comment]
Well, they are all HTTP request tools, and somewhat descendants of fetch in some way or form.
What's your definition of large? I think it's all relative.

**Comment by ivarconr** [comment]
I am leaning towards `node-fetch` for these reasons:

- It will be easier to create adapters for "fetch" and this have browser support
- It is light-weight 
- It supports what we need
