### ISSUE TITLE
If the custom headers functions fails, further fetches are not queued

### ISSUE THREAD

**Issue by AndreasChristianson** [Unleash/unleash-client-node#179]
If the [custom headers function](https://github.com/Unleash/unleash-client-node/blob/master/src/repository.ts#L107) rejects (for example during temporary network outage when refreshing a jwt), the [timed fetch](https://github.com/Unleash/unleash-client-node/blob/master/src/repository.ts#L121) never requeues. This leaves the client in a state where it is no longer attempting to refresh its cache from the unleash server.

This can be demonstrated by providing a [custom headers function](https://github.com/Unleash/unleash-client-node/blob/master/src/unleash.ts#L33) that fails every other call:

```
let callCount = 0;
const instance = initialize({
    url: 'http://unleash.herokuapp.com/api/',
    appName: 'my-app-name',
    instanceId: 'my-unique-instance-id',
    customHeaderFunction: () => new Promise((resolve, reject) => {
        if(++callCount % 2 === 0){
            reject();
        } else {
            resolve({
                myAuthHeader: 'secrets...'
            })
        }
    })
});
```
Using the above config, note that the client stops updating after the first failed refresh.

Potential solutions:
 - wrap the custom headers function call in a try/catch
 - move the `this.timedFetch()` above any user provided function calls

**Comment by ivarconr** [comment]
thanks for reporting.
