### ISSUE TITLE
CORS problem

### ISSUE THREAD

**Issue by gabrieligbastos** [Unleash/unleash-client-node#180]
Hi, Ideployed the server with docker and trying to use unleash api with my nuxt.js but running into CORS policy block. What would be the best solution?

**Comment by ivarconr** [comment]
Add proper cors header on there server? You can use the preRouterHook to do that. https://unleash.github.io/docs/getting_started#2-or-programmatically

**Comment by gabrieligbastos** [comment]
i see, it wont work for docker, right? =/

**Comment by sandeepbhatkande** [comment]
I am using Unleash proxy for accessing unleash server from browser (React project). I have started Unleash server in docker container. While using it is giving CORS problem beacuse both server are in different origin. please suggest how to set headers to unleash server.
