### ISSUE TITLE
The global `isEnabled`always returns false

### ISSUE THREAD

**Issue by nikksan** [Unleash/unleash-client-node#183]
## Expected Behavior
I would expect `Unleash.isEnabled` and `isEnabled` to work the same way or to update the docs to discourage the usage of the latter.
## Current Behavior
`isEnabled` always returns false, `Unleash.isEnabled` works as described

## Steps to Reproduce
1. Start a simple server

```
const unleash = require('unleash-server');

unleash
  .start({
    databaseUrl: 'postgres://username:password@localhost:5432/unleash',
    port: 4242,
  })
  .then(unleash => {
    console.log(
      `Unleash started on http://localhost:${unleash.app.get('port')}`,
    );
  });
```

2. Connect a client 
```
const { Unleash, isEnabled } = require('unleash-client');

const instance = new Unleash({
  appName: 'test-client',
  url: 'http://localhost:4242/api/',
  refreshInterval: 1000,
});

instance.once('ready', () => { // note that .once does not return a promise as suggested by the docs
  setInterval(() => {
    console.log(isEnabled('test'));
  }, 1000);
});

3. Toggle the feature on/off
```

**Comment by ivarconr** [comment]
Hi @nikksan ,

You are absolutely right, the last example in the README.md is totally wrong. Usually you allow the SDK to manage the global Unleash instance like this (as shown in most examples):

```js
const { initialize, isEnabled } = require('unleash-client');

const instance = initialize({
    appName: 'my-app-name',
    url: 'http://unleash.herokuapp.com/api/',
});

instance.once('registered', () => {
    // Do something after the client has registered with the server api.
    // NB! It might not have recieved updated feature toggles yet.
});

instance.once('changed', () => {
    console.log(`Demo is enabled: ${isEnabled('Demo')}`);
});
```

You may also instantiate  your own Unleash instance, but then you can't use the "global" `isEnabled` method, as it will not have access to your local Unleash instance, you will need to call `instance.isEnabled()` instead. 

Unleash should probably throw is isEnabled is called before an instance have been instantiated, explaining this in detail.

**Comment by ivarconr** [comment]
will be followed up as part of #209
