### ISSUE TITLE
react-native

### ISSUE THREAD

**Issue by vongohren** [Unleash/unleash-client-node#184]
Is this client clean enough to be used in a react native environment as well?
Or is it only supported by the web?

**Comment by ivarconr** [comment]
This client was never meant for web or native. The enterprise edition of Unleash has dedicated support for web an native via the Unleash-proxy.

**Comment by vongohren** [comment]
But in the Readme there is some mention of web. It says node but also
mentiones web at the same time. Is not that a bit confusing as you
explicitly say it's not for web?

**Comment by MrAlexWeber** [comment]
I'm chiming in because I'm trying to use Unleash with react-native as well. I'm running into an issue with the `os` dependency personally, so it seems like the answer is 'no' it's not supported in react-native.

**Comment by vongohren** [comment]
@MrAlexWeber thanks for chiming inn. Then I will set a hold on this as a tool for toggles
