### ISSUE TITLE
use unleash in aws lambda

### ISSUE THREAD

**Issue by escar** [Unleash/unleash-client-node#186]
I'm wondering what's the proper way to use unleash in AWS Lambda.
Read #116 but I can only make it work if I create the instance in the lambda handler and access the features in `instance.on('ready', () => {})`, like:

```
const handler =  (event, callback) => {
    const instance = initialize({
        url: 'https://app.unleash-hosted.com/light/api/',
        appName: 'app',
        instanceId: 'instance',
        customHeaders: { Authorization: 'token' },
    });

    instance.once('ready', () => {
        const enabled = isEnabled('myfeature');
       // works here
    });
    
    const enabled = isEnabled('myfeature');
    // does not work here
}
```
If I create the instance outside the handler, as @moolen suggested in that issue, still doesn't work.

As an alternative, tried to use the api directly (https://app.unleash-hosted.com/light/api/client/features/myfeature) but it's quite slow, compared with the npm package approach (200/300ms the former using axios, <10ms the latter).

Any help?

**Comment by escar** [comment]
I could eventually do:

```
await new Promise((resolve, reject) => {
     instance.on('ready', () => {
         resolve();
     });
});
```
but this doesn't look a wonderful solution...

**Comment by moolen** [comment]
```const handler =  (event, callback) => {
    const instance = initialize({
        url: 'https://app.unleash-hosted.com/light/api/',
        appName: 'app',
        instanceId: 'instance',
        customHeaders: { Authorization: 'token' },
    });

**Comment by moolen** [comment]
```javascript
const handler =  (event, callback) => {
    // dont do this:
    // initialize a new unleash instance on every lambda invocation (!)
    // internally this executes a setInterval()
    // after a few iterations your lambda will explode (and so will your unleash api server)
    const instance = initialize({
        url: 'https://app.unleash-hosted.com/light/api/',
        appName: 'app',
        instanceId: 'instance',
        customHeaders: { Authorization: 'token' },
    });
})
```

if you pull the `initialize()` out of the `handler`, it will soon be initialized, but not on the first execution.
This has a drawback of potentially losing metrics because the lambda can effectively be shut down without finishing all handlers.

**Comment by ivarconr** [comment]
Hi @escar ,

I missed your initial question in this thread. 

I see that you are a unleash-hosted customer. I would like to highlight that we do offer the [unleash proxy](https://www.unleash-hosted.com/articles/the-unleash-proxy/) as part of the Unleash-hosted offering. This provides a simpler integration in serverless environments. Please reach out on email or slack, and we can help you get started.

**Comment by escar** [comment]
Hi guys, thanks for your comments.

> if you pull the initialize() out of the handler, it will soon be initialized, but not on the first execution. It will also update itself properly.

@moolen well, if it doesn't work on the 1rst execution, then what's the point? We need it to be working all times. We plan to have provisioned concurrency for the lambda, but this doesn't seem the ideal solution to me.

@ivarconr we're still evaluating unleash hosted. How can we use the proxy? Also, what's the difference to using the api directly (like https://app.unleash-hosted.com/light/api/client/features/myfeature)? Although, as I pointed out, the api seems a bit slow.

thank you

**Comment by moolen** [comment]
> well, if it doesn't work on the 1rst execution, then what's the point

An implementation is always a trade-off (for instance `simple/complex`, `consistency/availability` etc.). This one in particular focuses on execution/response time. We say: i don't care if the toggle is not ready in the first execution (so it will return the sane fallback value) and at some point (nth execution) it will be ready and it will return the correct configured value.

An alternative approach would be to have a global variable that tracks the initialization state of unleash and wait in the first execution until unleash is ready. The following executions won't initialize unleash. 
:cactus:  This implementation will add latency in the 99th percentile to your API consumers - which might be tolerable or not. It wasn't for us because our traffic patterns has high spikes, needs to scale aggresively and fast. (latency-wise) this adds up quickly: `lambda warmup + unleash initialization time + higher load on unleash api-server`.

> We need it to be working all times

A note / a learning we've had: You ~shouldn't~ **can not** have a hard dependency on a feature-toggle. It will be unavailable at some point and your apps must function without it: I recommend to implement sane defaults into the applications. A feature-toggle **is not a configuration service** and your app must be resilient to such failures.

**Comment by escar** [comment]
Thanks @moolen.
Yes, there's always fallbacks, I understand it can and it will fail at some point. 

Currently we have feature toggling done with environment variables, which is not something a non-tech person can easily change, for example, for A/B testing.

I haven't tested it in a deployment environment, but if we have provisioned concurrency for the function, unleash whould be always initialized, no?

Anyway, it seems there's a few caveats using the node package on a lambda. That's why using the api seemed more consistent to me, although the time it takes worries me. 
Unleash proxy, on the other hand, seems interesting, if could get more info on it and how it differs from the api..

**Comment by moolen** [comment]
> provisioned concurrency [...] would be always initialized

That depends on the implementation: if initialized inside handler then it wouldn't be ready. If outside, then it should be.

**Comment by ivarconr** [comment]
> Unleash proxy, on the other hand, seems interesting, if could get more info on it and how it differs from the api..

So the API is quite different as it is super-fast and will evaluate toggles one the server-side, making integration simple. It is also designed to be hosted any-where and the recommended setup would be to run it as a small process in the same VPC as your AWS-lambda. Its basically a docker-container you deploy with some configuration, with low resource requirements. 

Unleash-hosted can also host the proxy for you, but then you would need to do the network request, adding network latency, no way to get around this.
