### ISSUE TITLE
Question: All flags for context

### ISSUE THREAD

**Issue by ericwooley** [Unleash/unleash-client-node#191]
How do you get all flags for a user context? I would like to use the feature flags on the front end as well, however, there doesn't seem to be a method for getting all the flags for a user.

I came up with this kind of hack:
```ts
  app.get('/auth/feature-flags', (req, res) => {
    const context = reqToUnleashContext(req)
    res.json(
      getFeatureToggleDefinitions()?.map((item) => {
        return { ...item, enabled: isEnabled(item.name, context) }
      }),
    )
  })
```
But it doesn't really feel like a good solution. 

Is it possible to pass a context into `getFeatureToggleDefinitions?` or is there another function I should be using?

**Comment by ivarconr** [comment]
Do you really want **all flags**, or just the flags used by the frontend?

**Comment by ericwooley** [comment]
I am using all the flags. At least for now. There isn't that many. If it gets to the point where I am worried about the size of the payload, thats probably a signal I need to close out some of the flags...

**Comment by ivarconr** [comment]
I think this can be useful. The only thing is that a "getAllTogglesForContext" should only returned enabled toggles, and can not report metrics, as it does not now if the toggles actually is used, just they evaluate to true for the given context

**Comment by manvydasu** [comment]
@ivarconr 
Why was this closed as completed? Seems like this feature was not implemented.
