### ISSUE TITLE
Question: global isEnabled vs instance.isEnabled

### ISSUE THREAD

**Issue by joeyrogues** [Unleash/unleash-client-node#196]
Good morning everyone :)

I was supprised to see that the suggested way to get a flag value is to use a global `isEnabled`.

I was expecting to have a isEnabled function on the instance.
And I was happy to realise that there is one.

I decided to experiment with the following code:

```js
const { initialize, isEnabled } = require('unleash-client')

const instance1 = initialize({
    url: 'http://localhost:4242/api/',
    appName: 'my-app-name',
    instanceId: 'my-unique-instance-id',
})

instance1.on('count', (name, enabled) => console.log(`first instance: isEnabled(${name}) returned ${enabled}`))

const instance2 = initialize({
    url: 'http://localhost:4243/api/',
    appName: 'my-app-name',
    instanceId: 'my-unique-instance-id',
})

instance2.on('count', (name, enabled) => console.log(`second instance: isEnabled(${name}) returned ${enabled}`))

setTimeout(() => {
  instance1.isEnabled("FIRST")
  instance2.isEnabled("FIRST")
  isEnabled("FIRST")
  
  instance1.isEnabled("SECOND")
  instance2.isEnabled("SECOND")
  isEnabled("SECOND")
}, 2000)
```

Here is the result:

```
isEnabled(FIRST) returned true
isEnabled(FIRST) returned false
isEnabled(FIRST) returned false
isEnabled(SECOND) returned false
isEnabled(SECOND) returned true
isEnabled(SECOND) returned true
```

My guess is that `isEnabled` references the last registered.

I believe it could be a good idea to document this behavior.

That being said, I understand that a usecase including 2 instances of unleash is a bit off.

What do you think?

In addition, would there be any drawbacks/problems using the `instance.isEnabled` function ?

**Comment by ivarconr** [comment]
Hi, 

Sorry for the delayed response. 

You are absolutely right `initialize` will also configure a "global" instance pointer, and it will always be the last configured one. 

There is nothing fundamentally different from using `isEnabled` over `instance.isEnabled`, when initialize have only been called once. 

If you intend to have multiple instances I would probably just call the unleash constructor directly instead: 


```js
const { Unleash } = require('unleash-client');

const instance = new Unleash({
    url: 'http://localhost:4243/api/',
    appName: 'my-app-name',
    instanceId: 'my-unique-instance-id',
});
``` 

This is exactly what `initialize` do [under the hood](https://github.com/Unleash/unleash-client-node/blob/master/src/index.ts#L9-L13), but you avoid the lib storing a reference to the instance. 

> I believe it could be a good idea to document this behavior.

Absolutely! If you are up for it a PR for this would be welcomed!

**Comment by ivarconr** [comment]
Updated docs for this

**Comment by joeyrogues** [comment]
Sorry for the late reply.
I wanted to say thank you for the clarification and documentation. :+1:
