### ISSUE TITLE
feat: add "synchronized" event

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash-client-node#209]
In a lot of scenarios you would like to block your application until the Unleash SDK has successfully synchronized with the Unleash API, to make sure you are not operating on an empty set of feature toggles or stale configurations (old backup)

Today you have the following events that you may subscribe on:

- `ready` event - Emitted when the Unleash SDK has read the local backup file. The backup file will often be empty in a immutable (docker) environment. 
- `changed` event - Emitted whenever the client SDK receives a non 304 response from the Unleash API. This will be emitted the first time the client SDK synchronizes, regardless of the state being exactly the same as the local backup. However, it is not entirely clear from the naming of the event that this will happen. 

I purpose we introduce a new event: 
- `synchronized` - Which will be emitted the first time the Client SDK receives toggle configurations from the Unleash API. 

This will address #181 and #183

**Comment by SimenB** [comment]
Could consider adding a promise to the instance as well, which is resolved whenever synchronization happens. Although it's not much code to handle that on the consumer side.


```js
import { once } from 'events';
import { Unleash } from 'unleash-client';

async function startUnleash() {
  const instance = new Unleash({});

  await once(instance, 'synchronized');

  return instance;
}
```

https://nodejs.org/api/events.html#events_events_once_emitter_name_options

An event probably still makes sense regardless since it's the model the client is built upon

**Comment by ivarconr** [comment]
How long should the promise hang around?

**Comment by SimenB** [comment]
IMO forever until it resolves (or an error occurs). If people want a timeout they can do `Promise.race` themselves
