### ISSUE TITLE
Unable to use client in a require-less environment

### ISSUE THREAD

**Issue by digital-h** [Unleash/unleash-client-node#219]
Unfortunately the examples do not work for me, as I do not use any `require`.
So I migrated them to the following approach:

```
import {initialize, Unleash} from 'unleash-client';

type Constructor<T> = { new (...args: any[]): T };

export function FeatureToggleMixin <B extends Constructor<any>>(base: B) {

  return class extends base {

    _unleash : Unleash;

    constructor(...args: any[]) {
      super(args);

      this._unleash = initialize({
        url: 'http://localhost:4242/api/',
        appName: 'my-app',
        instanceId: 'my-unique-instance-id',
      });

      this._unleash.on('ready', console.log.bind(console, 'ready'));
    }   
}
```

But when I try to run it, I get the following error-message:
```Uncaught SyntaxError: The requested module '../../../unleash-client/lib/index.js' does not provide an export named 'initialize'```

**Comment by ivarconr** [comment]
just for reference; are you using typescript?

I guess we should also target modules in or tsconfig:
https://blog.logrocket.com/publishing-node-modules-typescript-es-modules/

**Comment by digital-h** [comment]
Yes I am!

**Comment by ivarconr** [comment]
if you are using typescript there should not be any problem importing the Unleash Node SDK. I have put together a small example:
https://github.com/ivarconr/unleash-node-example/blob/main/index.ts

**Comment by digital-h** [comment]
Mmmh.. maybe it is, because I'm not using it in a backend node-environment, but with my frontend-application using [lit-element](https://lit-element.polymer-project.org/) / web-components

**Comment by digital-h** [comment]
Also I do not use common-js, but ES6.
So maybe an ESM wrapper for your CJS named exports might already be a solution to my problem.
