### ISSUE TITLE
Help: What unleash library to use for React-native

### ISSUE THREAD

**Issue by vedyed** [Unleash/unleash-client-node#221]
Hello,

Can anyone please tell me what library I can use to integrate Unleash into my react-native mobile application?

Does this package or https://github.com/unleash-hosted/unleash-proxy-client-js work?

**Comment by ivarconr** [comment]
> Does this package or https://github.com/unleash-hosted/unleash-proxy-client-js work?

we open a PR in that project to add react native support.
