### ISSUE TITLE
Make context in type definitions into an optional parameter to match the docs

### ISSUE THREAD

**Issue by azangru** [Unleash/unleash-client-node#222]
The example in the Readme currently features the following snippet:

```
unleash.on('synchronized', () => {
  // Unleash is ready to serve updated feature toggles.

  // Check a feature flag
  const isEnabled = unleash.isEnabled('some-toggle');

  // Check the variant
  const variant = unleash.getVariant('app.ToggleY');
});
```

Both `unleash.isEnabled('some-toggle')` and `unleash.getVariant('app.ToggleY')` will raise a typescript error, because the type definitions list `context` as a mandatory second parameter ([link](https://github.com/Unleash/unleash-client-node/blob/b04bc60d2b462f0e4cd89ef53cc4b5f4afc5d34f/src/unleash.ts#L199-L201))

However, it appears from the code that the `context` is just a key-value-pair object, in which none of the fields is required. This makes the whole `context` parameter optional. Could you please update your type definitions to reflect that?

**Comment by ivarconr** [comment]
Thanks for pointing this out. Will implement a fix for this soon.
