### ISSUE TITLE
add support for Repository.prototype.fetch to be able to receive request parameters

### ISSUE THREAD

**Issue by Albertobar94** [Unleash/unleash-client-node#226]
I had an issue with ca certificates since I am working with a custom ca from the company who I work for. Unfortunately, I have to modify the libraries code because I do not have an option include a custom certificate in the request to initialize unleash client... so basically in the post request using Repository.prototype.fetch the option to add ca would make it for this bug.

**Comment by Albertobar94** [comment]
in the request.js file
var httpsAgent = new https.Agent({
    keepAlive: true,
    keepAliveMsecs: 30 * 1000,
    timeout: 10 * 1000,
    ca: <Value to receive>,
});

**Comment by ivarconr** [comment]
We could potentially add support for custom SSL certificates. 

I wonder though, would it be possible to use the node option [NODE_EXTRA_CA_CERTS](https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file) to extend with your custom certificates as trusted by your application? I think this approach should work out of the box without changing the SDK.

**Comment by Albertobar94** [comment]
I could not make it work setting the environment at the first launch with that since my Mac is using the Company's CN... so to make it easier I saw I could use a custom ca in that setting.. or even a 'rejectUnauthorized: false' and still have a secure environment since the connection making me problem is becauase of a SELF_SINGED_CERTIFICATE_IN_CHAIN and we use this library at work... maybe I can help out with a PR?

**Comment by ivarconr** [comment]
> maybe I can help out with a PR

Yes please 👍

**Comment by austinmehmet** [comment]
@ivarconr @Albertobar94 - Any update on this?

I tried providing the `NODE_EXTRA_CA_CERTS` env var and it doesn't seem to do anything with Unleash. I have to already set this var for connection to my company's internal APIs and it works for that. 

Being able to set `rejectUnauthorized` to false for localhost would be helpful

**Comment by ivarconr** [comment]
I kind of lost track of this as I expected a PR for this. Would you be up for that @austinmehmet? If not I will try to schedule it for next week.

**Comment by austinmehmet** [comment]
@ivarconr I can see if I can try and carve out some time to put up a PR.

**Comment by ivarconr** [comment]
Thanks @austinmehmet

**Comment by austinmehmet** [comment]
Whats weird is that I ran into a different SSL issue and tried doing 

`require('https').globalAgent.options.ca = require('fs').readFileSync('my/companies/certs.crt')`

And that actually worked for this other issue, but again, for this unleash client it did nothing. I'm not super familiar with `make-fetch-happen`. I know the above library was using axios and maybe the difference in HTTP libraries is causing this? 

Anyway, I'll start working on a PR tomorrow morning to pass in {httpOptions: rejectUnauthorized: false} to the unleash client.
