### ISSUE TITLE
Extract strategies implementation to its own package

### ISSUE THREAD

**Issue by yordis** [Unleash/unleash-client-node#232]
In order to share the implementation in NodeJS and Browser environments, would be nice to set up some mono-repo or something and create some packages that allow us to share some code between those two environments.

**Comment by ivarconr** [comment]
This SDK is not meant to be used in a browser environment. Have you seen Unleash Proxy?https://docs.getunleash.io/sdks/unleash-proxy

**Comment by yordis** [comment]
Here is why I ask, https://github.com/fvoordeckers/react-unleash-flags/pull/19

Right now, our VP is giving us some granted push back with unleash because we are lacking mature implementation compare with others services, so either the proxy or the incoming React component, I would like to figure out what is the work required in order to get to a stage where we can have strong arguments against closed-source paid implementations.

So please help me here, I am here to support the project as much as I can.

**Comment by ivarconr** [comment]
With the proxy you already have a browser sdk with a react example. 

https://github.com/unleash-hosted/unleash-proxy-client-js/tree/master/examples/react-app

**Comment by ivarconr** [comment]
...we can also expose the strategy implementations out of the Node SDK. But evaluating the strategies inside the browser means that you are exposing the full configuration to everyone. Which might not be what you want.

**Comment by yordis** [comment]
> means that you are exposing the full configuration to everyone

Yeah ... about that ... don't tell people that we are doing that please!

**Comment by thomasheartman** [comment]
Hey, @yordis 👋🏼  Thanks for chasing off the stale bot here! I've had another look at this thread: is what you're trying to do evaluate toggles in the browser using the Node SDK? Is there any reason you can't use the proxy and a proxy client?

**Comment by yordis** [comment]
keep
