### ISSUE TITLE
Code 401 after updating from 3.40 to 3.8.0.

### ISSUE THREAD

**Issue by AlexanderN8** [Unleash/unleash-client-node#241]
After updating client-node version from 3.4.0 to 3.8.0 same code return: 
``Response was not statusCode 2XX, but was 401``

Thank you.

**Comment by ivarconr** [comment]
Which version of Unleash are you using?

**Comment by ivarconr** [comment]
fyo: until unleash-client `3.4` we used [request](https://www.npmjs.com/package/request) module, which have been deprecated. 

now unleash-client uses [make-fetch-happen](https://www.npmjs.com/package/make-fetch-happen). 

Can it be that you do any "request" magic behind the scenes?

**Comment by Kls82** [comment]
@ivarconr  Thank you for the quick response.  Indeed we have a proxy that adds tokens to headers. Is it really a different request from a proxy point of view?

**Comment by AlexanderN8** [comment]
@ivarconr Thank you for the quick response. Indeed we have a proxy that adds tokens to headers. Is it really a different request from a proxy point of view?

**Comment by ivarconr** [comment]
depends on how you intercept the call.
