### ISSUE TITLE
[Question] Why the strategy is evaluated in a OR fashion?

### ISSUE THREAD

**Issue by krysalead** [Unleash/unleash-client-node#243]
Hi,

I am curious because my use cases are more to evaluate in a AND way as I expected to match all the criteria to show the feature. 
Example:
I need my user to be logged in and on a VALIDATION phase.

That' will be super cool to have a notion of phase or environment (Alpha, Beta, Prod...) with the same feature but not the same state.

**Comment by ivarconr** [comment]
Hi,

Unleash will soon introduce support for environments (we are working hard to make that happen, and also part of it will be available as Open Source). 

to support AND scenario you will either: 
1. use the commercial version which supports [strategy constraints](https://docs.getunleash.io/advanced/strategy_constraints) or
2. implement a [custom activation strategy](https://docs.getunleash.io/advanced/custom_activation_strategy) where you can implement your own rules. (Available in open-source)

**Comment by krysalead** [comment]
Hi,

Thanks, I took the approach of forking and changing the défaut implementation with “every” instead of “some” during strategy evaluation.
For the time being, waiting for the environment feature.

Olivier DAUMAS
