### ISSUE TITLE
Client continue to send requests after failed registration

### ISSUE THREAD

**Issue by AlexanderN8** [Unleash/unleash-client-node#246]
Hello.
I noticed strange behavior when the request to _"api/client/register"_  returned with 401. The client continues to send requests to _"api/client/features"._ Is it a bug? 
Thank you.

**Comment by glensc** [comment]
Registration is optional:
- https://github.com/Unleash/unleash-client-node/issues/279

But in details it's probably written in specification:
- https://github.com/Unleash/client-specification
