### ISSUE TITLE
Build crashing when setting up Unleash Instance

### ISSUE THREAD

**Issue by bhopalg** [Unleash/unleash-client-node#247]
I have installed the unleash client sdk for node.js. When setting up a new instance and then running the application, I get the following error.

    [ng] ./node_modules/minimatch/minimatch.js:6:9-24 - Warning: Module not found: Error: Can't resolve 'path' in '/PATH/app/node_modules/minimatch'
    
    [ng] BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
    
    [ng] This is no longer the case. Verify if you need this module and configure a polyfill for it.
    
    [ng] If you want to include a polyfill, you need to:
    
    [ng]    - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
    
    [ng]    - install 'path-browserify'
    
    [ng] If you don't want to include a polyfill, you can use an empty module like this:
    
    [ng]    resolve.fallback: { "path": false }
    
    [ng] ./node_modules/promise-inflight/inflight.js:6:13-32 - Warning: Module not found: Error: Can't resolve 'bluebird' in '/PATH/app/node_modules/promise-inflight'
    
    [ng] Warning: /PATH/app/src/app/services/unleash-feature-tool/unleash-feature-tool.service.ts depends on 'unleash-client'. CommonJS or AMD dependencies can cause optimization bailouts.

package.json version installed `"unleash-client": "^3.10.1"`

Service

    import { environment } from 'src/environments/environment';
    import { Injectable } from '@angular/core';
    import { startUnleash } from 'unleash-client';
    import { Unleash } from 'unleash-client/lib/unleash';
    
    @Injectable({
      providedIn: 'root'
    })
    export class UnleashFeatureToolService {
    
      private unleash: Unleash;
    
      constructor() { }
    
      async setUpInstance(): Promise<void> {
        console.log({
          appName: environment.unleashServer.appName,
          url: environment.unleashServer.url,
          customHeaders: {
            Authorization: environment.unleashServer.authToken,
          },
        });
    
         this.unleash = await startUnleash({
          appName: environment.unleashServer.appName,
          url: environment.unleashServer.url,
          customHeaders: {
            Authorization: environment.unleashServer.authToken,
          },
        });
      }
    }

**Comment by ivarconr** [comment]
the node SDK cannot be used in a frontend application, you would need to look in to using the [Unleash Proxy](https://docs.getunleash.io/sdks/unleash-proxy) and the [proxy js sdk](https://docs.getunleash.io/sdks/proxy-javascript).
