### ISSUE TITLE
Gitlab: Disable registration

### ISSUE THREAD

**Issue by glensc** [Unleash/unleash-client-node#279]
I found accidentally why using environment does not work with gitlab node client, appears they have either misinterpreted the documentation and implemented it wrong, or it's just their specific things:

From https://github.com/Unleash/unleash-client-php#gitlab-specifics

> # GitLab specifics
> - In GitLab you have to use the provided instance id, you cannot create your own.
> - No authorization header is necessary.
> - Instead of app name you need to specify the GitLab environment.
> - For this purpose you can use withGitlabEnvironment() method in builder, it's an alias to withAppName() but communicates the intent better.
> - GitLab doesn't use registration system, you can set the SDK to disable automatic registration and save one http call.
> - GitLab doesn't read metrics, you can set the SDK to disable sending them and save some http calls.

So, to do the same for node client:
- [x] the GitLab environment must be passed as appName
- [x] disable metrics with `disableMetrics` key
- [ ] how to disable "registration"? (whatever that is)

**Comment by glensc** [comment]
Actually, the php client page explains what are registration and metrics:
- https://github.com/Unleash/unleash-client-php#client-registration
- https://github.com/Unleash/unleash-client-php#metrics

**Comment by glensc** [comment]
Seems in their documentation example they also swapped appName with environment for some reason:

```go
func init() {
    unleash.Initialize(
        unleash.WithUrl("https://gitlab.com/api/v4/feature_flags/unleash/42"),
        unleash.WithInstanceId("29QmjsW6KngPR5JNPMWx"),
        unleash.WithAppName("production"), // Set to the running environment of your application
        unleash.WithListener(&metricsInterface{}),
    )
}
```
- https://docs.gitlab.com/ee/operations/feature_flags.html#golang-application-example

**Comment by ivarconr** [comment]
Registration is part of the metrics feature. It should be sufficient to disable metrics. Does that not work for you?

**Comment by glensc** [comment]
Ok, that's good info, I don't know how to check which requests unleash makes. Is there a way to enable such debug logging?

**Comment by thomasheartman** [comment]
Hey, @glensc 👋🏼  Did you ever get to check whether disabling metrics is sufficient to solve your problem? I think you should be able to listen for the `registered` event (mentioned in the [events section of the readme](https://github.com/Unleash/unleash-client-node#events). If that never fires, then the client is never registered. Does that track?

**Comment by glensc** [comment]
yes. all work for me, here's my constructor:

```ts
    const environment = process.env.CI_ENVIRONMENT_NAME;
    const unleash = new Unleash(
      {
        url,
        instanceId,
        appName: environment,
        disableMetrics: true,
      }
    );
```

**Comment by thomasheartman** [comment]
Great! In that case, I'll go ahead and close this issue for now. Feel free to reopen it if there's more to be done ☺️
