### ISSUE TITLE
Update Documentation - Clearer client usage and required listeners and/or alternatives

### ISSUE THREAD

**Issue by cristobal** [Unleash/unleash-client-node#310]
## Bakground
We encountered that our applications where not starting up when they did could not reach the unleash server upon initialisation.
The reason for this is that the we neither had one of the following:
* `unleashClient.on('error', errorHandler)`
* `process.on('uncaughtException', errorHandler)`

I have an example project [here](https://github.com/cristobal/fastify-unleash-client-failure), that demos this as explained below:

### Application crashes
Due to this the application never started up or was disconnected as the picture here:
![Screenshot 2022-03-24 at 11 58 42](https://user-images.githubusercontent.com/155505/159926788-4c01a1cc-38e0-47dd-afae-90b9cd54aba3.png)

### Application still runs
However if we start up with either an unleash error listener and/or a process on uncaughtException, the application will still runs:
![Screenshot 2022-03-24 at 14 31 35](https://user-images.githubusercontent.com/155505/159927233-23b919c1-ea9f-4297-88c9-91d82820b42a.png)
Since the the emitted error from `minipass-fetch` package used surfaces at our user level scope, which seems to be documented in the code for minipass-fetch [here](https://github.com/npm/minipass-fetch/blob/main/lib/index.js#L115-L133).

##  It's already documented 🤷
Well i read the documentation and yes it's says with a small comment in the [Alternative usage](https://github.com/Unleash/unleash-client-node#alternative-usage) example:
![Screenshot 2022-03-24 at 14 39 01](https://user-images.githubusercontent.com/155505/159928651-d37a6efe-08f6-4473-8c62-640e8a4e6044.png)

Well it's long down in the client documentation, and  there is also a reference to some `require.cache`
![Screenshot 2022-03-24 at 14 40 26](https://user-images.githubusercontent.com/155505/159928830-597c381e-4397-423a-be88-591de3d77715.png)
which is only documented in the alternative usage example, it may seem that the documentation is out of date?

## Solution
It would be better and explicitly tell in the first example in the [Getting started](https://github.com/Unleash/unleash-client-node#getting-started) section for the [initialize unleash-client](https://github.com/Unleash/unleash-client-node#2-initialize-unleash-client) example to add the error handler here and/or specify under that a `unleashClient.on('error', errorHandler)` and/or `process.on('uncaughtException', errorHandler)` is needed and otherwise the application may be terminated…

I can contribute with a proposal to update the README.md in a separate PR, if you want. 
However the `require.cache` part may be out of date?

**Comment by ivarconr** [comment]
Thanks for raising this. I deferentially we need to update to documentation. 

> However the require.cache part may be out of date?
yes indeed!

**Comment by thomasheartman** [comment]
@cristobal As Ivar says, thanks for bringing this to our attention. I think your observations are spot on!

> I can contribute with a proposal to update the README.md in a separate PR, if you want.

I'd love that 😄 Feel free to tag me if you have any further questions about it or anything.  Does that sound alright to you? ☺️
