### ISSUE TITLE
Path is undefined in version 3.13.1

### ISSUE THREAD

**Issue by dswhitely1** [Unleash/unleash-client-node#316]
<img width="892" alt="image" src="https://user-images.githubusercontent.com/45896739/162000272-df481a1a-da8e-4631-8ed0-101f30de128b.png">
<img width="542" alt="image" src="https://user-images.githubusercontent.com/45896739/162000408-a2a713f2-8d60-499d-b94a-c425b3205576.png">

The above code is throwing a TypeError about path argument must be a string, received undefined.  I'm not seeing anything in the documentation about a path needing to be passed in on the initialize method.  Downgrading to 3.13.0 fixes this TypeError.

**Comment by ivarconr** [comment]
Solved in `v3.13.2`. 
I did a small mistake when taking our the 3.13.1 release, sorry about that!
