### ISSUE TITLE
Extend getFeatureToggleDefinitions function in order to support tag filtering

### ISSUE THREAD

**Issue by Gaspar1234** [Unleash/unleash-client-node#337]
### Describe the feature request

Hello guys,

I'm trying to retrieve features given a tag using the sdk but I didn't find a way to do it.

I'm using the function called: `getFeatureToggleDefinitions` but this does not support any kind of filter and the entity returned does not includes tags associated to feature.

I saw that http API supports this using query parameters, it's possible do something similar here?

### Solution suggestions

could be something like this

`getFeatureToggleDefinitions(tags?: Array<TagFilter>): FeatureInterface[];`

or if this possible add tags in the `FeatureInterface` in order to filter by myself using that tag.

**Comment by Tymek** [comment]
SDK will fetch definitions and keep it up to date in the background, not when calling `instance.getFeatureToggleDefinitions()`. You can **specify tags on initialization**, as explained here: [readme#advanced-usage](https://github.com/Unleash/unleash-client-node#advanced-usage). I hope this covers your use case. We will consider adding tags to the output of feature definitions in the future, so that it's possible to filter it afterwards.

**Comment by Gaspar1234** [comment]
Thanks for the answer, 

I'm using tags on initialization, this is my case:

I' start the client with this tags: "X", "Y", "Z", then I want to expose a endpoint to retrieve only features for one of them, for example "X", In this scenario I have to get features for "X", "Y", "Z" and after that I'm filtering using a prefix in the name. 

What do you recommend do? **Should I initialize one client by tag**? **still filtering by substring in the name**? **or in this endpoint call the http API?**

Thanks again :D

**Comment by FredrikOseberg** [comment]
Hi @Gaspar1234 

Yes, you can instantiate different clients with different tag configurations to achieve what you want. If you instantiate them in the same context in your application and use the same refreshInterval they should be able to stay in sync with negligible difference. 

If you are using the pro / enterprise version you could group the feature toggles in a project and use the project name to filter the toggles.

It would be interesting to learn more about your use-case and architecture. Would you have time to flesh out your example?
