### ISSUE TITLE
Fallback value is not working correctly for inaccessible api endpoint

### ISSUE THREAD

**Issue by jstn455** [Unleash/unleash-client-node#359]
### Describe the bug

If I were to initialize unleash with a wrong URL that does not resolve, my `isEnabled('feature-flag', {}, false)` calls resolve to true instead of the fallbackValue of false.  I believe it's because the isEnabled call on [this line ](https://github.com/Unleash/unleash-client-node/blob/main/src/index.ts#L35) is calling a function which takes in a [function as the third argument](https://github.com/Unleash/unleash-client-node/blob/main/src/client.ts#L56), not a boolean.  Maybe that is messing things up.

If the instance cannot make successful calls to the API endpoint, I'd expect the fallbackValue to be used instead.

### Steps to reproduce the bug

```
    let unleash: Unleash | undefined
    try {
      unleash = await startUnleash({
        url: 'http://blah',
        appName: 'env',
        instanceId: 'instanceId',
        refreshInterval: 60 * 1000,
      });
    } catch (error) {
      logger.error(`Could not start unleash: ${error}`);
    }
    logger.info(`value is ${isEnabled('feature-flag', {}, false)}`); // returns true
```

### Expected behavior

I expect the fallback value to be used when the unleash client cannot connect to an api endpoint successfully.

### Unleash version

3.15.10

**Comment by andreas-unleash** [comment]
Hi @jstn455 , thank you for reporting this. I believe this has been resolved [#339](https://github.com/Unleash/unleash-client-node/pull/339)
