### ISSUE TITLE
feature-request: support context for getFeatureToggleDefinitions (or update docs regarding it's usage)

### ISSUE THREAD

**Issue by manvydasu** [Unleash/unleash-client-node#360]
### Describe the feature request

It's a bit unclear to understand reason for `getFeatureToggleDefinitions` - it returns all the feature flags, but it is not user specific (context can not be passed). Seems like in traditional architecture, which has BE server and SPA in frontend, it could be used as a way to retrieve all feature flags from BE and passing those to frontend. However, it does not support context - and custom strategies (i.e. UserIdStrategy) for feature flags can't be used.

### Solution suggestions

Looks like it would be better to support `getFeatureToggleDefinitions` for specific context. In such case, metrics should probably be not updated - since if all flags are returned, it's unclear which ones will be used by the user.

Or documentation could be updated, to indicate use cases for getFeatureToggleDefinitions - perhaps it should not be used  for passing all feature flags to frontend.

**Comment by sighphyre** [comment]
Hi manvydasu,

Thanks for pointing this out, I think our docs here are probably a little wanting here. Just to give you a bit of context here about the method, this isn't useful for getting feature toggle states, this is for getting the raw data as sent by the Unleash server, this is very much before things like strategies have been evaluated and not all of the SDKs have an equivalent method. We added this in response to requests to support some fairly unusual usecases (like iterating all the toggle names and debugging strategy configurations), it's not part of a common flow of using Unleash and most applications would never need to consume this method.

If you're interested in the usecase you've pointed out here - sending toggles to an SPA in a pre-evaluated state, you're probably looking for the Unleash Proxy (https://docs.getunleash.io/sdks/unleash-proxy) and one of the associated proxy clients.

I'm going to update the docs to make it a bit clearer that this not for getting the state of a all the feature toggles but rather the raw data from the server.

Thanks again for pointing this out!

**Comment by lucas-silveira** [comment]
I would like to get all features by user from server-side. I would not like to start a Unleash Proxy for that...
