### ISSUE TITLE
Throw/warn if multiple versions loaded

### ISSUE THREAD

**Issue by sveisvei** [Unleash/unleash-client-node#38]

**Comment by ivarconr** [comment]
Do you have any suggestions on how to implement this @sveisvei?

**Comment by sveisvei** [comment]
@ivarconr Sure,

```js

if (global.unleashClientLoaded) {
 // warn or throw
}
global.unleashClientLoaded = true;
```

**Comment by ivarconr** [comment]
closed via https://github.com/Unleash/unleash-client-node/commit/2543cc34a24a7e57592bb2d85eb5b10245e22493
