### ISSUE TITLE
Add support for custom HTTP headers

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash-client-node#42]
see https://github.com/Unleash/unleash-client-java/pull/35 for reference.

**Comment by sveisvei** [comment]
@ivarconr did a quick first pass: is this enough? https://github.com/Unleash/unleash-client-node/compare/master...custom-headers?expand=1

**Comment by ivarconr** [comment]
Looks like it :) 

(A bit hard to review it properly on my mobile)

**Comment by sveisvei** [comment]
Closed by https://github.com/Unleash/unleash-client-node/pull/43
