### ISSUE TITLE
startUnleash functions doesn't return when called multiple times

### ISSUE THREAD

**Issue by fox1t** [Unleash/unleash-client-node#441]
### Describe the bug

`startUnleash` is supposed to return a singleton. Per definition, it should return the same instance when invoked multiple times. What happens, instead, is that it works only when invoked the first time. From the second on, the instance is not returned.

### Steps to reproduce the bug

Use the repro repo at https://github.com/fox1t/unleash-bug
Instead of logging two console logs, only the first one is visible.

### Expected behavior

The `startUnleash` invoked function returns the instance correctly when called multiple times.

### Additional context

A possible fix is to emit the `synchronized` event inside the `getIntance` method.
```ts
if (Unleash.instance) {
	if (configSignature !== Unleash.configSignature) {
		throw new Error(
			"You already have an Unleash instance with a different configuration.",
		);
	}
	process.nextTick(() => Unleash.instance.emit("synchronized"));
	return Unleash.instance;
}
```

### Unleash version

4.22.1

### Subscription type

Pro

### Hosting type

Hosted by Unleash

### SDK information (language and version)

3.19.0

**Comment by ivarconr** [comment]
Oh, interesting. It has been like this sense the startUnleash function was added 2 years ago. It was not intended to be called multiple times, but I agree that it should have supported that. 

I think we can simply fix it by exposing a `isSynchronized()` method on the Unleash instance and simply check that as an alternative to awaiting the synchronized event. 

Something like:

```ts

export async function startUnleash(options: UnleashConfig): Promise<Unleash> {
  const unleash = initialize(options);
  if(!unleash.isSyncronized()) {
     await once(unleash, 'synchronized');
  }
  return unleash;
}
```

Are you up for providing a PR @fox1t ?

**Comment by fooddilsn** [comment]
@ivarconr In agreement with @fox1, I can take care of it.
