### ISSUE TITLE
Dependency problem using with webpack

### ISSUE THREAD

**Issue by ddetoni** [Unleash/unleash-client-node#48]
Hi,

I tried to use the unleash client in a React application and seems that one of the dependencies have some problem with webpack.

`Critical dependencies:
1:476-483 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/ajv/dist/ajv.bundle.js 1:476-483`

Seems that the request module is not updated and one of the sub dependencies is causing this.

**Comment by SimenB** [comment]
This is only meant to be used in node, there is no client for the browser (yet)

**Comment by ivarconr** [comment]
Thanks for you interest in the profjext @ddetoni!

This client is not meant for the browser and thus depends on request, which might be hard to bundle with webapack.

Exposing the unleash-api directly to the browser is genearally not adviced becuase of the the design decision where the unleash-api is rather stupid (basically a crud API) and most of the logic is inside the client implementation (to make it fast and scaleable). 

If you need to expose toggles to single-page apps you should consider a small proxy-service only exposing the toggles, briefly discussed in https://github.com/Unleash/unleash/issues/255. 

 I'm closing this issue for now. Feel free to re-open it if you don't find this response sufficient or have other information.

**Comment by ddetoni** [comment]
Hi @SimenB and @ivarconr 

Thanks for the answer. The application was not working at runtime, but I understand the problem right now and a proxy-service makes a lot of sense. Thanks again.

**Comment by davidlivingrooms** [comment]
> This is only meant to be used in node, there is no client for the browser (yet).

Hello @SimenB 👋, does this mean there are plans to do this?
