### ISSUE TITLE
Access to raw data

### ISSUE THREAD

**Issue by olehfitsyk** [Unleash/unleash-client-node#572]
### Describe the feature request

I'm building an extension for Unleash Proxy and would like to access the raw feature toggles configuration fetched from Unleash. I found that `getFeatureToggleDefinition` gives most of the information I need, with one exception. Unleash segments used in strategies are linked by id. And there's no way to access constraints configuration behind the segment.

### Solution suggestions

Expose method `getSegment(id: number)` from the repository similarly as `getFeatureToggleDefinitions` is implemented: Repository -> Unleash -> module exports.

**Comment by andreas-unleash** [comment]
Hi @olehfitsyk .  Seems sensible to me. I will discuss with the team and get back to you

**Comment by andreas-unleash** [comment]
Hi @olehfitsyk .  Thanks for the explanation.  Exposing the `getSegment` function is not something we would like to do, but we understand your need and we will find a way to support what you need.  I will post here when we have something

**Comment by olehfitsyk** [comment]
Hi @andreas-unleash, just tested the new version and it works perfectly. Thank you!
