### ISSUE TITLE
Replace vulnerable ip dependency

### ISSUE THREAD

**Issue by madsop-nav** [Unleash/unleash-client-node#586]
### Describe the feature request

Replace the ip library with for instance ip-address

### Background

The ip library has a severe CVE: https://github.com/indutny/node-ip/issues/136

**Comment by kwasniew** [comment]
Thanks for the report. We never use this package to distinguish between public and private IP addresses which is the core of the vulnerability. We're monitoring a PR with a fix anyway: https://github.com/indutny/node-ip/pull/138 and will apply it asap.

**Comment by Henning3110** [comment]
It seems there was a release this morning without the vulnerability: https://github.com/indutny/node-ip/releases/tag/v2.0.1

**Comment by gastonfournier** [comment]
@Henning3110 @madsop-nav we'll be patching 5.5.0 with this new version. Will that be enough for your use case?

**Comment by madsop-nav** [comment]
> @Henning3110 @madsop-nav we'll be patching 5.5.0 with this new version. Will that be enough for your use case?

Yes, that'd be sufficient indeed. Thanks!

**Comment by Henning3110** [comment]
Of course. Thank you for the quick implementation.

**Comment by gastonfournier** [comment]
https://github.com/Unleash/unleash-client-node/releases/tag/v5.5.1 is out, please reach out if there's any problem! Thanks!
