### ISSUE TITLE
Implement a few common strategies

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash-client-node#6]
Examples:
- userWithId
- gradualRolloutRandom
- byHostName
- byRemoteAddr

**Comment by Andersos** [comment]
What if we split out all the strategies in separate issues?

**Comment by ivarconr** [comment]
It's a great feeling closing issues. :+1:

**Comment by Andersos** [comment]
Should we close this for now?

**Comment by SimenB** [comment]
Was this ever done? Would be great not having to duplicate strategy implementations across apps

**Comment by sveisvei** [comment]
I agree, we should do this.

What common strategies could we implement with ease?

**Comment by SimenB** [comment]
The ones in the OP?

**Comment by sveisvei** [comment]
Ill start on a PR

**Comment by ivarconr** [comment]
Will be part of #33
