### ISSUE TITLE
Unleash client stops fetching

### ISSUE THREAD

**Issue by olehfitsyk** [Unleash/unleash-client-node#615]
### Describe the bug

We encountered an issue with Unleash Proxy a few times when it seemed that it stopped getting any updates from Unleash. It was caused by the update in unleash-client release 5.2 because it stops fetching Unleash configuration when it encounters status codes 401, 403 or 404. Please see `handleErrorCases` function. I agree that it seems like a configuration issue, but in my opinion, after the successful initial fetch, it doesn't make sense to just stop pulling updates from Unleash in case a single 404 is encountered.

### Subscription type

None

### Hosting type

None

**Comment by HenrikBacher** [comment]
Issue seems to have been introduced with #537 I think it would make sense to extend the retry logic to also cover 404 errors
