### ISSUE TITLE
Removed instance ID

### ISSUE THREAD

**Issue by daniluk4000** [Unleash/unleash-client-node#644]
### Describe the feature request

Hey guys. In new major you have remove instanceId, which was required for us to connect to Gitlab: https://docs.gitlab.com/ee/operations/feature_flags.html

Can you please restore it as an optional parameter? 

### Solution suggestions

If not, how can Gitlab possibly rework this on their side?

**Comment by sighphyre** [comment]
Hey @daniluk4000, sorry about that, that was a mistake on our side. We've released a new version with the instanceId restored

**Comment by daniluk4000** [comment]
> Hey @daniluk4000, sorry about that, that was a mistake on our side. We've released a new version with the instanceId restored

<3
