### ISSUE TITLE
Default to not creating files and clean up flies created during unit tests.

### ISSUE THREAD

**Issue by DevinCrumb** [Unleash/unleash-client-node#649]
### Describe the feature request

The Unleash Client is creating unwanted and prosibly problimatic files.  The application may not have permission to write to the directory used by the client or there may be other reasons where creating a file is problematic.  Default should be to not use the file system.

Also, when running the Unit Test, it creates files that it does not clean up.  The Unit test needs to make sure any files it creates, it deletes when the test ends, even when the test fails.

**Comment by ivarconr** [comment]
Hi, 

you can customize this behaviour yourself via a [custom store provider](https://github.com/Unleash/unleash-client-node?tab=readme-ov-file#custom-store-provider) and the Node SDK comes with the InMemStorageProvider: 

```js
import { initialize, InMemStorageProvider } from 'unleash-client';

const client = initialize({
  appName: 'my-application',
  url: 'http://localhost:3000/api/',
  customHeaders: { Authorization: '<YOUR_API_TOKEN>' },
  storageProvider: new InMemStorageProvider(),
});
```
