### ISSUE TITLE
Static configuration

### ISSUE THREAD

**Issue by elhoyos** [Unleash/unleash-client-node#74]
Have you considered having the client to use a static configuration file instead of a server?

### Use case
Your project is not a big one, you don't need metrics and just have small set of features to toggle, so you should not need a server and sorts to make this work.

### Proposal

```js
const features = {
    'my-feature': {
        name: 'my-feature',
        enabled: true,
        strategies: [{
            name: 'technology',
            parameters: {
                device_category: 'mobile'
            }
        }],
        variants: [
            [{
                name: 'control'
            }, {
                name: 'my-way'
            }]
        ]
    }
};
const { initialize } = require('unleash-client');
const unleash = initialize({ features });
```

Where `features` could be a properly formed object or a json filepath string.

**Comment by ivarconr** [comment]
Yes we have been talking about it previously. I think it is a great idea. 

Also this would possibly make it easier to run standardized tests across client SDKs, which verifies that they implement common strategies correctly, without having to mock out network calls and such.

**Comment by elhoyos** [comment]
I have made something in https://github.com/elhoyos/unleash-client-node/compare/variations...elhoyos:static-features

@ivarconr: given all these variations features still has some road ahead before getting into trunk, do you believe we should land these into a branch?

**Comment by ivarconr** [comment]
Yes, it would be nice to land this as it own feature and not clutter it together with the variants support. :+1:
