### ISSUE TITLE
Why do strategies need to be defined in the client?

### ISSUE THREAD

**Issue by batjko** [Unleash/unleash-client-node#97]
Hi,

I am a bit confused why the client needs to define the strategy that will be used to distribute flags (i.e. using the `strategies` property and custom  `new Strategy()` instances).

I have a custom strategy set up in the Unleash UI, one that has a list parameter (`tenantCode`), so that, if I have a number of tenantCodes defined, I want to set a flag to true if the client's context includes one of those tenantCodes.

Or in pseudo code: 
```if client.tenantCode is included in flag.params.tenantCodes, then true.```

Now, the client doesn't care about the implementation of this flag, it just wants to send up its context and receive a `true` or `false` value.
And yet, I get a "missing strategy" error from unleash-client, if I don't define the exact logic of `isEnabled()` for this custom strategy inside my consumer code.

Also, if multiple clients are consumers of that flag (with that tenant strategy), now *all* of them need to have that custom logic implemented and defined as a custom strategy.

This is very weird to me. Imagine I have 6 microservices and 3 different web and mobile apps, all using my tenant Strategy above (for various flags). Some written in Javascript/Node, some in Go, some in Java, some Python.
I am now forced to re-implement the custom Strategy and `isEnabled()` function in all of them, making sure the different languages don't treat the flag differently because of course they're supposed to be treated identically (by the nature of a server-controlled flag).

Can someone clarify why it is designed this way?
Other systems don't require this (e.g. LaunchDarkly): You define the flag logic on the server and the clients are only responsible for sending up user context and receive back the `true`/`false` state of a given flag the client is interested in.

**Comment by ivarconr** [comment]
> Can someone clarify why it is designed this way?

The short answer is that strategies came before context. 

Today I would have designed it more in line with your suggestions. I have for some time been thinking that we should support a generic `ContextStrategy`, which basically should allow you to combine context parameters in any way you wish. Such a strategy would naturally replace all "built-in" strategies, making unleash easier to use. 

I still think it makes sense to have a custom-strategy extension point, when the requirements goes beyond what one could express as part of the context.

**Comment by batjko** [comment]
> The short answer is that strategies came before context.
Ah, that makes sense.

As we're only starting with Unleash, we don't have a lot of consumers just yet, so it's not a big problem for me so far. I just thought I'd ask, in case I misunderstood something.

For now, to make the definition of the strategy in the consumer easier and more functional, I have rewritten the class example from the docs like this:

The following assumes a TenantSegregation strategy set up on the server, with a list of tenant Codes as a parameter:
```js
// in an internal npm package, e.g.  "flags-client", exposing the TenantSegregation and any other custom strategies:

const isTenantEnabled = (params, context) =>
  params.tenantCodes
    .replace(' ', '')
    .toLowerCase()
    .split(',')
    .includes(context.tenantCode.toLowerCase().trim())

export const generateStrategy = (name, isEnabledFunc) => ({
  ...new Strategy(name),
  isEnabled: isEnabledFunc,
})

export const TenantSegregationStrategy = generateStrategy(
  'TenantSegregation',
  isTenantEnabled,
)
```

```js
// in my consuming app or service:

const instance = initialize({
  url: `${config.flags-url}/api/`,
  appName: config.appName,
  instanceId: Date.now(),
  started: new Date().toISOString(),
  strategies: [TenantSegregationStrategy],
  interval: 10000,
})

// [...]

console.log('test.foo flag: ', isEnabled('test.foo', { tenantCode: 'ACME' } ))
```
Works like a charm, relegates the strategy logic into a shareable package, and gets rid of classes for a more functional usage pattern (if one is so inclined, as I tend to be).
