### ISSUE TITLE
Could not find package.json up from ./node_modules/pkginfo/lib/pkginfo.js when using with react

### ISSUE THREAD

**Issue by lekhasy** [Unleash/unleash-client-node#98]
I have tried unleash-client with react application which created with create-react-app.
It's brand new app and I have change nothing but import `initialize` in App.js file:
`import {initialize} from 'unleash-client';`

That line cause the application break with the following message:
`Could not find package.json up from ./node_modules/pkginfo/lib/pkginfo.js`

**Comment by SimenB** [comment]
The client is not meant to run in the browser, it's meant to be used server side

**Comment by lekhasy** [comment]
@SimenB Do the team have any plan for web support?
I saw there are lots of reuseable code in this repo.
We only have to change some in storage stuffs.

**Comment by SimenB** [comment]
I don't know, @ivarconr?

**Comment by ivarconr** [comment]
There is no plans to support browsers today. This has already been discussed in https://github.com/Unleash/unleash-client-node/issues/62
